CREATE DATABASE IF NOT EXISTS DB202DWESLoginLogoffTema5;
USE  DB202DWESLoginLogoffTema5;

CREATE USER IF NOT EXISTS 'user202DWESLoginLogoffTema5'@'%' IDENTIFIED BY 'paso';
GRANT ALL PRIVILEGES ON DB202DWESLoginLogoffTema5.* TO 'user202DWESLoginLogoffTema5'@'%';

CREATE TABLE IF NOT EXISTS T01_Usuario(
T01_CodUsuario CHAR(15) PRIMARY KEY,
T01_Password VARCHAR(64),
T01_DescUsuario VARCHAR(255),
T01_NumConexiones INT DEFAULT 0,
T01_FechaHoraUltimaConexion DATETIME DEFAULT NULL,
T01_Perfil ENUM('usuario','administrador') DEFAULT 'usuario',
T01_ImagenUsuario BLOB)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS T02_Departamento(
T02_CodDepartamento CHAR(3) PRIMARY KEY,
T02_DescDepartamento VARCHAR(255) DEFAULT NULL,
T02_FechaCreacionDepartamento DATETIME DEFAULT CURRENT_TIMESTAMP,
T02_VolumenDeNegocio FLOAT DEFAULT NULL,
T02_FechaBajaDepartamento DATETIME DEFAULT NULL)ENGINE=InnoDB;